var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var c,e=[];!(c=a.next()).done;)e.push(c.value);return e};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
(function(){function a(){c(e.section).target.forEach(function(a){b.instances.has(a)||new b(a)})}var c=window.sg.common.$q,e={section:".notification-bar"},b=function(a){var d=this;this.selector={section:e.section,btn:".notification-bar__toggle-btn",hidden:".notification-bar__toggle-btn .hidden",content:".notification-bar__inner",nomarl:".notification-bar__column--collapsed",expend:".notification-bar__column--expanded"};this.timer=null;this.ele={window:c(window),section:c(a),btn:null,content:null,nomarl:null,
expand:null};this.handler={resize:function(){d.ele.section.css({height:""});d.timer&&clearTimeout(d.timer);setTimeout(function(){d.setHeight()},400)}};this.setProperty();b.instances.set(a,this);this.init()};b.prototype.setProperty=function(){this.ele.btn=this.ele.section.find(this.selector.btn);this.ele.hidden=this.ele.section.find(this.selector.hidden);this.ele.content=this.ele.section.find(this.selector.content);this.ele.pdBanner=this.ele.section.find(this.selector.pdBanner);this.ele.nomarl=this.ele.section.find(this.selector.nomarl);
this.ele.expand=this.ele.section.find(this.selector.expend)};b.prototype.init=function(){this.bindEvents()};b.prototype.reInit=function(){this.setProperty();this.bindEvents()};b.prototype.setHeight=function(){this.ele.section.css({height:this.ele.content.outerHeight()+"px"})};b.prototype.bindEvents=function(){var a=this;this.ele.btn.off("click").on("click",function(){a.ele.section.hasClass("is-expanded")?a.closeBanner():a.openBanner()});this.ele.window.off("resize",this.handler.resize).on("resize",
this.handler.resize);this.setHeight()};b.prototype.openBanner=function(){this.ele.section.addClass("is-expanded");this.ele.section.attr("aria-expanded",!0);this.ele.nomarl.hide();this.ele.expand.show();this.ele.hidden.innerHTML("Click to Collapse");this.setHeight()};b.prototype.closeBanner=function(){this.ele.section.removeClass("is-expanded");this.ele.section.attr("aria-expanded",!1);this.ele.nomarl.show();this.ele.expand.hide();this.ele.hidden.innerHTML("Click to Expand");this.setHeight()};b.instances=
new WeakMap;window.sg.components.notificationBar={init:a,reInit:function(){c(e.section).target.forEach(function(a){b.instances.has(a)?b.instances.get(a).reInit():new b(a)})},closeBanner:function(a){a=void 0===a?!0:a;c(e.section).target.forEach(function(d){b.instances.has(d)&&b.instances.get(d).closeBanner(a)})}};c.ready(a)})();
(function(){var a=window.sg.common.$q,c=window.sg.common.swiperManager,e=null,b=null,g=function(){e.find(".usp-banner__desc").target.forEach(function(b){b=a(b);var d=b.attr("data-an-page-track"),c=b.attr("data-an-headline-text");b.find("a").target.forEach(function(a){a.setAttribute("an-tr","ft17_usp banner-"+d+"-text-link");a.setAttribute("an-ca","content click");a.setAttribute("an-ac","feature");a.setAttribute("an-la","usp banner:"+c)})});e.target.forEach(function(b){var d=a(b);if(d.hasClass("usp-banner--bg-dynamic")){var f=
d.find(".swiper-container");b=function(){f.find(".swiper-slide-active").hasClass("dynamic--bg-light-gray")?(d.addClass("dynamic--bg-light-gray"),d.removeClass("dynamic--bg-blue")):f.find(".swiper-slide-active").hasClass("dynamic--bg-blue")&&(d.addClass("dynamic--bg-blue"),d.removeClass("dynamic--bg-light-gray"))};c.getSwiper(f.target[0]).on("transitionEnd",b);b()}})},d=function(){b.target.forEach(function(b){b=a(b);1===b.find(".usp-banner__icon").target.length&&("ltr"===window.sg.common.utils.getDirection()?
b.find(".usp-banner__desc").css({"text-align":"left"}):"rtl"===window.sg.common.utils.getDirection()&&b.find(".usp-banner__desc").css({"text-align":"right"}))})},h=function(){window.sg.common.image.initAll();e=a(".usp-banner");b=a(".usp-banner__contents");e.target.length&&b.target.length&&(g(),"mobile"===window.sg.common.utils.getCurrentDevice()&&d())};a.ready(h);window.sg.components.uspBanner={init:h,reInit:function(){a(".usp-banner").find(".basic-swiper").target.forEach(function(a){c.getSwiper(a)?
c.slideReInit(a):c.slideInit(a)});g()}}})();
(function(){var a=window.sg.common.$q,c=window.sg.common.utils.makeDate,e=window.sg.common.utils.getTimeStatus,b=function(a){this.els={el:a,liveOffEl:a.querySelector(".fn13-bambuser-fab__live-off-link"),liveOnEls:a.querySelectorAll(".fn13-bambuser-fab__live-on-link")};this.isShowFAB=!1;this.init()};b.prototype.init=function(){b.instances.has(this.els.el)||(b.instances.set(this.els.el,this),this.bindEvents())};b.prototype.bindEvents=function(){for(var a=0;a<this.els.liveOnEls.length;a++){var b=e(this.els.liveOnEls[a].dataset.liveOnStartTime,
this.els.liveOnEls[a].dataset.liveOnEndTime);if("live"===b){this.els.liveOffEl.classList.remove("show");this.els.liveOnEls[a].classList.add("show");this.isShowFAB=!0;break}else if("before"===b){b=new Date;var f=c(this.els.liveOnEls[a].dataset.liveOnStartTime);f.setMinutes(f.getMinutes()-30);f<=b&&(this.els.liveOffEl.classList.add("show"),this.isShowFAB=!0)}else"after"===b&&(b=new Date,f=c(this.els.liveOnEls[a].dataset.liveOnEndTime),f.setMinutes(f.getMinutes()+30),f>=b&&(this.els.liveOffEl.classList.add("show"),
this.isShowFAB=!0))}this.isShowFAB||(this.els.el.style.display="none")};b.instances=new WeakMap;var g={initAll:function(){[].concat($jscomp.arrayFromIterable(document.querySelectorAll(".fn13-bambuser-fab"))).forEach(function(a){b.instances.has(a)||new b(a)})}};window.sg.components.bambuserFab=g;a.ready(function(){return g.initAll()})})();